# Generated by Django 4.2.11 on 2025-08-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('especie', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('porte', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('microchip_codigo', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
